### ISSUE TITLE
Mines spawned outside that are successfully defused, have their scrap fall through the world.

### ISSUE THREAD

**Issue by Roobotics** [alipali737/Landmine-Scrap#2]
With a mod like 'HazardsOutside' the defused scrap you spawn, seems to tumble right through the outdoor floor, maybe it's being spawned in too low for mines that have any sort of tilt to them(all mines in facility are flat, even on stairs), Or different collider considerations for outdoor terrain perhaps, unsure, but it **almost** seems to work. Unfortunately I've yet to collect a scrap-rewarded for any outdoor defuse attempts/tests.

**Comment by alipali737** [comment]
Issue fixed in next release
